@startuml logical port updated
Controller->SGApp:_update_local_port(self,lport,original_lport)
activate SGApp
note over SGApp
    ssecgroups = lport.security_groups
    original_secgroups = original_lport.security_groups

    added_secgroups, removed_secgroups, unchanged_secgroups = self._get_added_and_removed_and_unchanged_secgroups(secgroups, original_secgroups)
end note
alt not secgroups and original_secgroups:
    ' # uninstall ct table
    SGApp->SGApp:_uninstall_connection_track_flows(lport)
end
loop secgroup in added_secgroups:
    SGApp->SGApp:_add_local_port_associating(lport, secgroup.id)
end
loop secgroup in removed_secgroups:
    SGApp->SGApp:_remove_local_port_associating(original_lport, secgroup.id)
end
loop secgroup in unchanged_secgroups:
    SGApp->SGApp:_update_port_addresses_process(lport, original_lport,secgroup.id)
    ' # delete conntrack entities by port addresses changed
    SGApp->SGApp:_delete_conntrack_entries_by_local_port_info(lport, original_lport, secgroup.id)
end
alt secgroups and not original_secgroups:
    ' # install ct table
    SGApp->SGApp:_install_connection_track_flows(lport)
end
deactivate
@enduml