@startuml create dhcp port
Neutron->DFDHCPModule:_create_dhcp_port
activate DFDHCPModule
DFDHCPModule->df_utils:subnet_project =get_obj_topic(subnet)
note over DFDHCPModuole
    port = {
    'port': {'project_id': subnet_project,
    'tenant_id': subnet_project,
    'network_id': subnet['network_id'], 'name': '',
    'admin_state_up': True, 'device_id': '',
    'device_owner': n_const.DEVICE_OWNER_DHCP,
    'mac_address': n_const.ATTR_NOT_SPECIFIED,
    'fixed_ips': [{'subnet_id': subnet['id']}],
    'status': n_const.PORT_STATUS_ACTIVE}
    }
end note
DFDHCPModule->core_plugin:create_port(context, port)
deactivate
@enduml