@startuml on subnet udpate
Neutron->DFDHCPModule:_subnet_udpate_handler
activate DFDHCPModule
DFDHCPModule->kwargs:context = ['context']
DFDHCPModule->kwargs:subnet = ['subnet']
DFDHCPModule->kwargs:orig_subnet = ['original_subnet']
alt DFDHCPModule->DFDHCPModule:_is_dhcp_state_change(orig_subnet, subnet)
    alt _is_subnet_enable_dhcp(orig_subnet)
        DFDHCPModule->DFDHCPModule:_remove_dhcp_subnet_from_network(context,subnet['network_id'],subnet)
    else _is_subnet_enable_dhcp(subnet)
        DFDHCPModule->DFDHCPModule:_add_dhcp_subnet_to_network(context,subnet['network_id'],subnet)
    else
        note over DFDHCPModule
            LOG.error("Subnet dhcp changed but neither old_subnet or"
            "new subnet do not enabled dhcp")
        end note
    end
end
deactivate
@enduml