@startuml logical port remote bind
Controller->SGApp:_add_remote_port(self,lport)
activate SGApp
note over SGApp
    secgroups = lport.security_groups
end note
alt not secgroups
    SGApp-->SGApp
end
loop secgroup in secgroups:
    SGApp->SGApp:_add_remote_port_associating(lport, secgroup.id)
end

deactivate
@enduml