@startuml bind port
Neutron->DFMechDriver:bind_port
activate DFMechDriver
note over DFMechDriver
    Set porting binding data for use with nova.
end note
' Prepared porting binding data
loop segment in context.segments_to_bind
    alt _check_segment(segment)
        DFMechDriver->context:set_binding(segment[api.ID],self.vif_type,self.vif_details,status=self.port_status)

        DFMechDriver-->Neutron
    else
        note over DFMechDriver
            LOG.debug("Refusing to bind port for segment ID %(id)s, "
            "segment %(seg)s, phys net %(physnet)s, and "
            "network type %(nettype)s",
            {'id': segment[api.ID],
            'seg': segment[api.SEGMENTATION_ID],
            'physnet': segment[api.PHYSICAL_NETWORK],
            'nettype': segment[api.NETWORK_TYPE]})
        end note
    end
end
deactivate DFMechDriver
@enduml