@startuml remote port unbound
Controller->DNATApp:_remote_port_unbound(self,lport)
activate DNATApp
'  # In case the port is flagged as in process, remove flag and ignore
alt self._pop_in_process(lport.id):
    DNATApp-->DNATApp:
end
alt floatingip in self._get_floatingips_by_lport(lport):
    DNATApp->DNATApp:_uninstall_remote_floatingip(floatingip)
end
alt floatingip in self._get_floatingips_by_floating_lport(lport):
    DNATApp->DNATApp:_uninstall_remote_floatingip(floatingip, emit_unbind=False)
end
deactivate
@enduml