@startuml logicalport remote bind
Controller->TunnelingApp:_add_remote_port(self,lport)
activate TunnelingApp
TunnelingApp->lport:lswitch = lswitch
TunnelingApp->lswitch:network_type = network_type
alt network_type not in self.tunnel_types:
    TunnelingApp-->TunnelingApp:
end
TunnelingApp->lswitch:segmentation_id = segmentation_id
TunnelingApp->TunnelingApp:_add_egress_dispatch_flow(lport, segmentation_id)
TunnelingApp->lswitch:network_id = unique_key
TunnelingApp->LOG:info("adding remote %(net_type)s lport %(lport)s",{'net_type': network_type,'lport': lport})
TunnelingApp->local_networks:add_remote_port(port_id=lport.id,network_id=network_id,network_type=network_type)
TunnelingApp->TunnelingApp:_modify_egress_bum_flow(network_id,network_type,segmentation_id,self.ofproto.OFPFC_ADD)
deactivate
@endstart