@startuml l3
class LogicalRouter {
    ports LogicalRouterPort[]
    routes HostRoute[]
}
class LogicalRouterPort {
    mac string
    lswitch LogicalSwitch
    network IpNetowrk
}
class FloatingIp {
    floating_ip_address IpAddress
    fixed_ip_address IpAddress
    lport LogicalPort 
    floating_lport LogicalPort
    lrouter LogicaRouter
}
class HostRoute {
    destionation IpNetwork required
    nexthop IpAddress required
}
class LogicalPort {

}
LogicalRouter*-->HostRoute
@enduml