@startuml router updated
DB->L3AppMixin:router_updated
activate L3AppMixin
L3AppMixin->L3AppMixin:_update_router_interfaces(original_router, router)
activate L3AppMixin
note over L3AppMixin
    A router has been updated. Delete old router ports, and create new
    router ports
    :param old_router:  The old router instance
    :type old_router:   LogicalRouter model
    :param new_router:  The new router instance
    :type new_router:   LogicalRouter model
end note

loop old_port in old_ports
    alt old_port not in new_ports
        L3AppMixin->L3AppMixin:_delete_router_port(new_router, old_port)
    end
end
loop new_port in new_ports:
    loop new_port not in old_ports:
        L3AppMixin->L3AppMixin:_add_new_router_port(new_router, new_port)
    end
end
deactivate
L3AppMixin->L3AppMixin:_update_router_attributes(original_router, router)
activate L3AppMixin
note over L3AppMixin
    A router has been updated. Update the followin attributes:
    * extra routes
    :param old_router:  The old router instance
    :type old_router:   LogicalRouter model
    :param new_router:  The new router instance
    :type new_router:   LogicalRouter model
end note

loop old_route in old_routes
    alt old_route not in new_routes
        L3AppMixin->L3AppMixin:_delete_router_extra_route(new_router, old_route)
    end
end
loop new_route in new_routes
    alt new_route not in old_routes
        L3AppMixin->L3AppMixin:_add_router_extra_route(new_router, new_route)
    end
end
deactivate
deactivate
@enduml