@startuml  logical local unbind
Controller->PortSecApp:_remove_local_port(self,lport)
activate PortSecApp
PortSecApp->lport:enable = port_security_enabled
alt enable
    PortSecApp->PortSecApp:_uninstall_port_security_flows(lport)
else
    PortSecApp->PortSecApp:_uninstall_disable_flow(lport)
end
deactivate
@enduml